import React, { useContext } from 'react'
import Head from 'next/head'
import Nav from '../components/Nav'
import { ModalProvider } from '../components/ModalContext'
import ModalX from '../components/ModalX'
import styles from '../styles/Home.module.css'

export default function Home() {


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ModalProvider>
        <Nav />
        <main className={styles.main}>
          <ModalX
            title='Josh'
            link='https://www.youtube.com/embed/e3RnAUvCS2Q'
          />
          <ModalX
            title='Rob'
            link='https://www.youtube.com/embed/ZBZ6BqoUDsU'
          />
        </main>
      </ModalProvider>

    </div>
  )
}
